# Generated by Django 3.0.2 on 2020-02-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='published_at',
        ),
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
