# Generated by Django 3.0.2 on 2020-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200203_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='anonymous_creator',
            field=models.BooleanField(default=False),
        ),
    ]
