# Generated by Django 3.0.2 on 2020-02-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_response_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=40)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll')),
            ],
            options={
                'unique_together': {('poll', 'ip_addr')},
            },
        ),
    ]
