# Generated by Django 3.0.2 on 2020-02-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_pollsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Option')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.PollSubmission')),
            ],
        ),
    ]
